if(EXISTS "/home/runner/work/sample-moments/sample-moments/_codeql_build_dir/test/test_TwoNumberStatistics[1]_tests.cmake")
  include("/home/runner/work/sample-moments/sample-moments/_codeql_build_dir/test/test_TwoNumberStatistics[1]_tests.cmake")
else()
  add_test(test_TwoNumberStatistics_NOT_BUILT test_TwoNumberStatistics_NOT_BUILT)
endif()
